// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SAFARIROMCOM;

namespace SAFARIROMCOM.Migrations
{
    [DbContext(typeof(SafariContext))]
    partial class SafariContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SAFARIROMCOM.Safari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LocationLastSeen");

                    b.Property<int>("NumberOfTimesSeen");

                    b.Property<string>("species");

                    b.HasKey("Id");

                    b.ToTable("Trip");
                });
#pragma warning restore 612, 618
        }
    }
}
